// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOSlK4zLc08KrNpQE1HqpT_OnfN63C974',
    appId: '1:826392776023:web:6f1522a348d267a2ff8212',
    messagingSenderId: '826392776023',
    projectId: 'habit-tracker-app-78710',
    authDomain: 'habit-tracker-app-78710.firebaseapp.com',
    storageBucket: 'habit-tracker-app-78710.firebasestorage.app',
    measurementId: 'G-NKX31K0FSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDol_V3N-MMU33Hdl9DkSBvXmWcm7jkQc4',
    appId: '1:826392776023:android:c08b8caca6356adeff8212',
    messagingSenderId: '826392776023',
    projectId: 'habit-tracker-app-78710',
    storageBucket: 'habit-tracker-app-78710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-ab0uxk1onuT5xOOL-vPpG5WnxzDPjk',
    appId: '1:826392776023:ios:187fe6a16f72493fff8212',
    messagingSenderId: '826392776023',
    projectId: 'habit-tracker-app-78710',
    storageBucket: 'habit-tracker-app-78710.firebasestorage.app',
    iosBundleId: 'com.hugo83.habitTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOSlK4zLc08KrNpQE1HqpT_OnfN63C974',
    appId: '1:826392776023:web:5d3dee5bc358beacff8212',
    messagingSenderId: '826392776023',
    projectId: 'habit-tracker-app-78710',
    authDomain: 'habit-tracker-app-78710.firebaseapp.com',
    storageBucket: 'habit-tracker-app-78710.firebasestorage.app',
    measurementId: 'G-RS8PTJDZK2',
  );
}
